/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as IngresarRouteImport } from './routes/ingresar'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as PoliticaPrivacidadRouteImport } from './routes/politica-privacidad'
import { Route as UbicacionRouteImport } from './routes/ubicacion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IngresarRoute = IngresarRouteImport.update({
  id: '/ingresar',
  path: '/ingresar',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadRoute = PoliticaPrivacidadRouteImport.update({
  id: '/politica-privacidad',
  path: '/politica-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const UbicacionRoute = UbicacionRouteImport.update({
  id: '/ubicacion',
  path: '/ubicacion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/horarios': typeof HorariosRoute
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/horarios': typeof HorariosRoute
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/horarios': typeof HorariosRoute
  '/ingresar': typeof IngresarRoute
  '/panel': typeof PanelRoute
  '/politica-privacidad': typeof PoliticaPrivacidadRoute
  '/ubicacion': typeof UbicacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/horarios'
    | '/ingresar'
    | '/panel'
    | '/politica-privacidad'
    | '/ubicacion'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/horarios'
    | '/ingresar'
    | '/panel'
    | '/politica-privacidad'
    | '/ubicacion'
  id:
    | '__root__'
    | '/'
    | '/horarios'
    | '/ingresar'
    | '/panel'
    | '/politica-privacidad'
    | '/ubicacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HorariosRoute: typeof HorariosRoute
  IngresarRoute: typeof IngresarRoute
  PanelRoute: typeof PanelRoute
  PoliticaPrivacidadRoute: typeof PoliticaPrivacidadRoute
  UbicacionRoute: typeof UbicacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingresar': {
      id: '/ingresar'
      path: '/ingresar'
      fullPath: '/ingresar'
      preLoaderRoute: typeof IngresarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidad': {
      id: '/politica-privacidad'
      path: '/politica-privacidad'
      fullPath: '/politica-privacidad'
      preLoaderRoute: typeof PoliticaPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ubicacion': {
      id: '/ubicacion'
      path: '/ubicacion'
      fullPath: '/ubicacion'
      preLoaderRoute: typeof UbicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HorariosRoute: HorariosRoute,
  IngresarRoute: IngresarRoute,
  PanelRoute: PanelRoute,
  PoliticaPrivacidadRoute: PoliticaPrivacidadRoute,
  UbicacionRoute: UbicacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
